allow user to View a separate page for each topic with a list of rela…
brunoFernandes21/nc-news pull request #6
Opened 2023-07-20 09:17 UTC by brunoFernandes21

…ted articles

2023-07-20 09:39 UTC, Beth-McCormack requested changes
Have a look at my comment and please submit another PR when done⭐️

2023-07-20 09:39 UTC, Beth-McCormack commented on src/components/TopicPage.jsx
> +  const filterArticlesByTopic = articles.filter((article) => {
This is filtering the articles on the front end, you should be utilising back end queries for this. Have a look at axios in the NC notes to see how to do this😁

2023-07-21 07:57 UTC, RichardNeat requested changes
Hey nice work so far. I know you were having some issues with this so drop me a message if you need another push. We do need to avoid filtering on the front end. Have a look and then resubmit please.

2023-07-21 07:57 UTC, RichardNeat commented on src/components/ArticleList.jsx
> +  console.log(topic)
please remove console logs before committing :)

2023-07-21 07:57 UTC, RichardNeat commented on src/components/testtopicpage.jsx
> +        // const articles = await fetchAllArticles(topic);
Please remove comment

2023-07-21 07:57 UTC, RichardNeat commented on src/components/testtopicpage.jsx
> +  const filterArticlesByTopic = articles.filter((article) => {
We should be achieving this filtering on the back end rather than the front end please. Beth suggested some good notes to help with this :)

2023-07-21 08:05 UTC, brunoFernandes21 commented on src/components/testtopicpage.jsx
> +  const filterArticlesByTopic = articles.filter((article) => {
Hey Rich. This is a component that I am not using at the moment. I was meant to remove it. which I have just done. This was an old component. The filtering is not happening here in this file. I will submit a new pull request without this file. and it should all work.

2023-07-21 08:25 UTC, RichardNeat commented on src/components/ArticleList.jsx
> +  if (topic === "coding") {
We could make this a bit more DRY potentially

2023-07-21 08:26 UTC, RichardNeat commented on src/components/testtopicpage.jsx
> +  const filterArticlesByTopic = articles.filter((article) => {
Understood, thanks for the update. All good to merge then :)

2023-07-21 08:32 UTC, brunoFernandes21 commented on src/components/testtopicpage.jsx
> +  const filterArticlesByTopic = articles.filter((article) => {
Sweeeeeet

2023-07-21 08:50 UTC, merged